CREATE PROCEDURE GETUSERSANDROLESDATA
AS
BEGIN
	SELECT ID AS ID, USERNAME As Name, EMAIL AS Email, PHONENUMBER AS Phone, ACCESSFAILEDCOUNT AS FailCount, LOCKOUTENABLED AS Lockout,
	LOCKOUTEND AS LockEnd, PASSWORDHASH AS Password
	FROM USERS;

	SELECT ID AS ID, UserID AS UserID, ROLEID AS RoleID FROM USERROLES;

	SELECT ID AS ID, ROLENAME AS Name, ROLEDESC AS Description FROM ROLES;
END

