CREATE PROCEDURE REGISTERUSER(
@USERNAME NVARCHAR(256),
@EMAIL NVARCHAR(256),
@PASSWORD NVARCHAR(256)
)
AS
BEGIN
	DECLARE @RETURNCODE INT;
	DECLARE @USEREXISTS BIT;

	SET @USEREXISTS = 0;

	SELECT @USEREXISTS = 1
	FROM USERS U
	WHERE U.USERNAME = @USERNAME

	IF @USEREXISTS = 1
		BEGIN
			SET @RETURNCODE = -1 -- USERNAME ALREADY EXISTS, REGISTER FAILED
		END
	ELSE
		BEGIN
			SET @RETURNCODE = 1  -- USERNAME DOESN'T EXISTS, REGISTER USER IN RECORD
			INSERT INTO USERS(USERNAME, EMAIL, PASSWORDHASH, LOCKOUTENABLED, ACCESSFAILEDCOUNT)
			VALUES(@USERNAME, @EMAIL, @PASSWORD, 0, 0)
		END
	SELECT @RETURNCODE AS RETURNVALUE;
END

