CREATE TABLE ROLES
(ID INT PRIMARY KEY NOT NULL,
ROLENAME NVARCHAR(50) NULL,
ROLEDESC NVARCHAR(500) NULL
);

CREATE TABLE USERS
(ID INT IDENTITY PRIMARY KEY NOT NULL,
USERNAME NVARCHAR(256) NULL,
EMAIL NVARCHAR(256) NULL,
PHONENUMBER NVARCHAR(100) NULL,
ACCESSFAILEDCOUNT INT NOT NULL,
LOCKOUTENABLED BIT NOT NULL,
LOCKOUTEND DATETIME NULL
);

CREATE TABLE USERROLES
(ID INT IDENTITY PRIMARY KEY NOT NULL,
USERID INT NOT NULL FOREIGN KEY REFERENCES USERS(ID),
ROLEID INT NOT NULL FOREIGN KEY REFERENCES ROLES(ID)
);


